### ISSUE TITLE
unable to add chrome extension - package is invalid could not unzip extension

### ISSUE THREAD

**Issue by alvinpradeep** [ucbvislab/d3-deconstructor#4]
hi getting error while installing extension. 
"package is invalid could not unzip extension"

**Comment by jodonnell-broadsoft** [comment]
Did the chrome web store solve this issue for you? If not, what did you fix? My app is having the same error.

**Comment by Disorrder** [comment]
@jodonnell-broadsoft Did you packed on linux or another OS like that? I've packed on linux and tried unpack on windows, and got this error too. When I put it in linux Chrome's extensions, works fine

**Comment by harperj** [comment]
@Disorrder that's good to know.  I haven't managed to reproduce this on OS X, but I don't have access to a Windows machine at the moment to test it out on.

**Comment by alexrosenfeld10** [comment]
Hi, getting the same issue occurring now. Not sure how to get around this

**Comment by dailenspencer** [comment]
Has anyone resolved this issue? I am having the same error and no bug reports on why its occuring.

**Comment by alexanderrosenfeldfmr** [comment]
Can't remember 100% what I did but I think it was because I wasn't admin.

**Comment by 2q1w2007** [comment]
Maybe there are some Non-ASCII characters in the extension.
