### ISSUE TITLE
Cannot build extension from source

### ISSUE THREAD

**Issue by yaph** [ucbvislab/d3-deconstructor#6]
I tried to build the extension from source as described in the Readme. When I run the browserify task, I get the following error:

    Running "browserify:injected" (browserify) task
    >> Error: Cannot find module 'jQuery' from '/repos/d3-deconstructor/node_modules/d3-decon-lib/src'
    Warning: Error running grunt-browserify. Use --force to continue.

    Aborted due to warnings.

I tried copying jquery.js to that location, but this didn't help and would have been a dirty workaround anyway I guess. There is a jquery directory in node_modules.

**Comment by harperj** [comment]
Thanks for the bug report.  Unfortunately I'm having trouble reproducing it.  

Could you share what node version you're using as reported by `node -v` and also the output from `npm --loglevel verbose install` as a file?

**Comment by yaph** [comment]
The node version is 0.10.25 running on Ubuntu 14.10, I put the output of the other command in this gist https://gist.github.com/yaph/c4c3fd29b402775cf311

Hope this help!
