### ISSUE TITLE
Con not change values for deconstructed file

### ISSUE THREAD

**Issue by stevevaius** [ucbvislab/d3-deconstructor#7]
After installing extension, I tried the examples you gave both static and in video examples to modify it by right side menu but there is no menu on down right side as showing in your video to modify the values. Only you can view the code parameters but no allowed modification
![image](https://cloud.githubusercontent.com/assets/15230282/11717161/41d77df4-9f57-11e5-87de-853dcc15c4c5.png)

**Comment by harperj** [comment]
Sorry, but this feature hasn't yet been released.  I'd like to ensure a consistent user experience before publishing it.
