### ISSUE TITLE
Un inquietud

### ISSUE THREAD

**Issue by Pacsangon** [ucbvislab/d3-deconstructor#8]
Buenas. Trato de iniciar la extención de chrome, pero se queda en una pantalla negra con unas letras de "Deconstructing". El error que surge en la consola es: Uncaught TypeError: el.getTransformToElement is not a function  

Si puede decir la forma de corregirlo, por favor. Agradezco su tiempo.

**Comment by harperj** [comment]
I don't think I'd be able to reply effectively in Spanish, but I believe I've solved your problem.  In a newer version of Chrome, the SVG API this project depended on changed.  I've used a polyfill (added in ffc0653), or you can just install the newest version from the Chrome Web Store.

**Comment by Pacsangon** [comment]
Le agradezco por su ayuda, harperj, funciona genial la extensión d3 deconstructor con la actualización de Chrome.
