### ISSUE TITLE
is there anything like a d3-restyler?

### ISSUE THREAD

**Issue by TracyYXChen** [ucbvislab/d3-deconstructor#9]
The D3-deconstructor paper says it has a pair of tools, for deconstructing and restyling, but seems the d3-constructor didn't allow users to change mappings or data values, so is there anything like a d3-restyler but not released?

**Comment by magrawala** [comment]
We were never able to release the restyling component of the work. But it might not be that difficult to recreate. You might also try working with this version of the deconstructor as it is a more recent and updated version: https://github.com/enamulh/d3-deconstructor-v3
